sudo: required

language: generic

services:
- docker

before_install:
- echo "start creating an image with dockerfile"
- docker build -t valueor/docker-react-app -f Dockerfile.dev

script:
- docker run -e CI=true valueor/docker-react-app npm run test -- --coverage

after_success:
- echo "Test Success"

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react-app
  env: DockerReactApp-env
  bucket_name: elasticbeanstalk-us-east-1-675758166233
  bucket_path: docker-react-app
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  scret_access_key: $AWS_SECRET_ACCESS_KEY